EletrosDomesticos/Models/EletroDomestico.cs
namespace EletrosDomesticos.Models
{
    public abstract class EletroDomestico
    {
        public string Marca { get; set; }
        public string Modelo { get; set; }
        public double ConsumoEnergetico { get; set; }

        public abstract string ExibirDetalhes();
    }
}

EletrosDomesticos/Models/ErrorViewModel.cs
namespace EletrosDomesticos.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

EletrosDomesticos/Models/Geladeira.cs
namespace EletrosDomesticos.Models
{
    public class Geladeira : EletroDomestico
    {
        public int CapacidadeLitros { get; set; }
        public bool TemFreezer { get; set; }

        public  override string ExibirDetalhes()
        {
            return $"Marca: {Marca}, Modelo {Modelo}, Capacidade {CapacidadeLitros}, Possui Freezer? {TemFreezer}";
        }
    }
}

EletrosDomesticos/Models/Televisor.cs
namespace EletrosDomesticos.Models
{
    public class Televisor : EletroDomestico
    {
        public int TamanhoTela { get; set; }
        public bool EhSmart { get; set; }

        public override string ExibirDetalhes()
        {
            return $"Marca: {Marca}, Modelo {Modelo}, Consumo: {ConsumoEnergetico}, Tela: {TamanhoTela}, Smart {(EhSmart? "Sim" : "Não")}";
        }
    }
}

EletrosDomesticos/Controllers/EletroDomesticoController.cs
using EletrosDomesticos.Models;
using Microsoft.AspNetCore.Mvc;

namespace EletrosDomesticos.Controllers
{
    public class EletroDomesticoController : Controller
    {
        public IActionResult Index()
        {
            List<EletroDomestico> eletros = new List<EletroDomestico>
            {
                new Televisor { Marca = "Samsung", Modelo = "NeoQLED", ConsumoEnergetico = 75, TamanhoTela = 22, EhSmart = true},
                new Televisor { Marca = "Samsung", Modelo = "MicroLED", ConsumoEnergetico = 50, TamanhoTela = 110, EhSmart = true },
                new Geladeira { Marca = "ElectroLux", Modelo = "Frost Free", CapacidadeLitros = 454, TemFreezer = true }
            };
            return View(eletros);
        }
    }
}

EletrosDomesticos/Controllers/HomeController.cs
using EletrosDomesticos.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace EletrosDomesticos.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

EletrosDomesticos/Views/EletroDomestico/Index.cshtml
@model List<EletroDomestico>

    <h1>Tabela de funcionalidade de Eletro Domésticos</h1>  

    <table class = "table table-striped table-bordered">
        <thead>
            <tr>
                <th>Marca</th>
                <th>Modelo</th>
                <th>Consumo Energético</th>
                <th>Capacidade</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var eletros in Model)
            {
                <tr>
                    <td>@eletros.Marca</td>
                    <td>@eletros.Modelo</td>
                    <td>@eletros.ConsumoEnergetico</td>
                    <td>
                        @if (eletros is Geladeira)
                    {
                        <strong>Tem Freezer:</strong> @(((Geladeira)eletros).TemFreezer ? "Sim" : "Não") <br/>
                    }
                    else if (eletros is Televisor)
                    {
                        <strong>SMART: </strong> @(((Televisor)eletros) .EhSmart? "Sim" : "Não")
                    }
                </td>
                </tr>
            }
        </tbody>
    </table>

EletrosDomesticos/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://learn.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

EletrosDomesticos/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - EletrosDomesticos</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/EletrosDomesticos.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">EletrosDomesticos</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="EletroDomestico" asp-action="Index">Eletro Domésticos</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - EletrosDomesticos - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>